/**
 * About / credits. Reachable from the title screen and the topbar.
 *
 * Dismissable, unlike the draft — nothing here is a decision.
 */
import { TID } from '../testids.ts';
import { btn, el, on } from './dom.ts';
import { Modal } from './modal.ts';
import type { UICtx } from './types.ts';

export const KOFI_URL = 'https://ko-fi.com/maxnovich';
/** Source. Linked from the menu so players can read it — and file bugs. */
export const REPO_URL = 'https://github.com/Kvadratni/tokenmaxxing';

interface CreditLine {
  readonly what: string;
  readonly how: string;
}

const CREDITS: readonly CreditLine[] = [
  { what: 'Code', how: 'Vanilla TypeScript. No framework, no game engine.' },
  { what: 'Pixel art', how: 'Generated by a committed script — npm run art redraws every sprite.' },
  { what: 'Audio', how: 'Synthesised live with WebAudio. There are no sound files.' },
  { what: 'Dependencies', how: 'None at runtime. The whole game is one bundle.' },
];

/** Opens a link in a new tab without handing it a window reference. */
function extLink(parent: HTMLElement, href: string, text: string, cls: string, tid?: string) {
  const a = el('a', { cls, text, parent });
  a.setAttribute('href', href);
  a.setAttribute('target', '_blank');
  a.setAttribute('rel', 'noopener noreferrer');
  if (tid) a.setAttribute('data-testid', tid);
  return a;
}

export class About {
  readonly modal: Modal;
  private readonly disposers: Array<() => void> = [];

  constructor(parent: HTMLElement, _ctx: UICtx) {
    this.modal = new Modal({
      tid: TID.aboutModal,
      label: 'About Tokenmaxxing',
      dismissable: true,
      cls: 'tm-about',
      // `Modal` reports the dismissal; closing is the owner's job.
      onDismiss: () => this.close(),
    });
    parent.appendChild(this.modal.el);

    el('h2', { cls: 'tm-modal__title', text: 'About', parent: this.modal.panel });
    el('p', {
      cls: 'tm-modal__sub',
      text:
        'A roguelike idle clicker about producing slop. Your wallet is the ship bar, ' +
        'so every purchase is the same question: invest now, or grind to the finish?',
      parent: this.modal.panel,
    });

    const list = el('dl', { cls: 'tm-about__credits', parent: this.modal.panel });
    for (const c of CREDITS) {
      el('dt', { text: c.what, parent: list });
      el('dd', { text: c.how, parent: list });
    }

    const foot = el('div', { cls: 'tm-about__foot', parent: this.modal.panel });
    el('p', {
      cls: 'tm-about__thanks',
      text: 'Free, and staying that way. If it made you smile, you can buy me a coffee.',
      parent: foot,
    });
    extLink(foot, REPO_URL, 'Source on GitHub', 'tm-btn tm-btn--quiet', TID.repoLink);
    extLink(foot, KOFI_URL, 'Support on Ko-fi', 'tm-btn tm-btn--kofi', TID.kofiLink);

    const close = btn({
      cls: 'tm-btn',
      tid: TID.aboutClose,
      text: 'Close',
      parent: foot,
    });
    this.disposers.push(on(close, 'click', () => this.close()));
  }

  get isOpen(): boolean {
    return this.modal.isOpen;
  }

  open(): void {
    this.modal.open(null);
  }

  close(): void {
    this.modal.close();
  }

  toggle(): void {
    if (this.modal.isOpen) this.close();
    else this.open();
  }

  destroy(): void {
    for (const d of this.disposers) d();
    this.disposers.length = 0;
    this.modal.destroy();
  }
}
