// GENERATED BY tools/art/build-art.mjs. Do not edit by hand.
// Run `npm run art` to regenerate.
import type { AtlasManifest } from './atlas-types.ts';

const manifest: AtlasManifest = {
  sheets: {
    rooms: new URL('../../public/sprites/rooms.png', import.meta.url).href,
    stage: new URL('../../public/sprites/stage.png', import.meta.url).href,
  },
  sprites: {
    room_bedroom: { sheet: 'rooms', frames: [{ x: 0, y: 0, w: 320, h: 180 }] },
    room_coworking: { sheet: 'rooms', frames: [{ x: 0, y: 180, w: 320, h: 180 }] },
    room_openplan: { sheet: 'rooms', frames: [{ x: 0, y: 360, w: 320, h: 180 }] },
    room_datacenter: { sheet: 'rooms', frames: [{ x: 0, y: 540, w: 320, h: 180 }] },
    room_orbital: { sheet: 'rooms', frames: [{ x: 0, y: 720, w: 320, h: 180 }] },
    human_body: { sheet: 'stage', frames: [{ x: 1, y: 1, w: 320, h: 180 }] },
    human_eyes_tired: {
      sheet: 'stage',
      frames: [
        { x: 152, y: 571, w: 59, h: 12, ox: 131, oy: 47 },
        { x: 212, y: 571, w: 59, h: 12, ox: 131, oy: 47 },
        { x: 272, y: 571, w: 59, h: 12, ox: 131, oy: 47 },
      ],
      fps: 1,
    },
    human_eyes_impatient: {
      sheet: 'stage',
      frames: [
        { x: 121, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 181, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 241, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
      ],
      fps: 1,
    },
    human_eyes_furious: {
      sheet: 'stage',
      frames: [
        { x: 420, y: 571, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 1, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 61, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
      ],
      fps: 1,
    },
    human_eyes_suspicious: {
      sheet: 'stage',
      frames: [
        { x: 301, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 361, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
        { x: 421, y: 589, w: 59, h: 11, ox: 131, oy: 47 },
      ],
      fps: 1,
    },
    human_mug: {
      sheet: 'stage',
      frames: [
        { x: 398, y: 182, w: 88, h: 96, ox: 229, oy: 84 },
        { x: 1, y: 333, w: 88, h: 96, ox: 229, oy: 84 },
        { x: 90, y: 333, w: 88, h: 96, ox: 229, oy: 84 },
      ],
      fps: 3,
    },
    human_typing: {
      sheet: 'stage',
      frames: [
        { x: 179, y: 333, w: 193, h: 66, ox: 64, oy: 114 },
        { x: 1, y: 430, w: 193, h: 66, ox: 64, oy: 114 },
      ],
      fps: 7,
    },
    human_chair: { sheet: 'stage', frames: [{ x: 303, y: 182, w: 94, h: 118, ox: 113, oy: 39 }] },
    agent_idle: {
      sheet: 'stage',
      frames: [
        { x: 343, y: 430, w: 36, h: 50 },
        { x: 380, y: 430, w: 36, h: 50 },
      ],
      fps: 1,
    },
    agent_squash: {
      sheet: 'stage',
      frames: [
        { x: 1, y: 497, w: 36, h: 50 },
        { x: 38, y: 497, w: 36, h: 50 },
      ],
      fps: 12,
    },
    agent_panic: {
      sheet: 'stage',
      frames: [
        { x: 417, y: 430, w: 36, h: 50 },
        { x: 454, y: 430, w: 36, h: 50 },
      ],
      fps: 10,
    },
    agent_sweat: {
      sheet: 'stage',
      frames: [
        { x: 75, y: 497, w: 36, h: 50 },
        { x: 112, y: 497, w: 36, h: 50 },
      ],
      fps: 3,
    },
    agent_dazed: {
      sheet: 'stage',
      frames: [
        { x: 195, y: 430, w: 36, h: 50 },
        { x: 232, y: 430, w: 36, h: 50 },
      ],
      fps: 4,
    },
    agent_wait: {
      sheet: 'stage',
      frames: [
        { x: 149, y: 497, w: 36, h: 50 },
        { x: 186, y: 497, w: 36, h: 50 },
      ],
      fps: 3,
    },
    agent_grovel: {
      sheet: 'stage',
      frames: [
        { x: 269, y: 430, w: 36, h: 50 },
        { x: 306, y: 430, w: 36, h: 50 },
      ],
      fps: 6,
    },
    agent_mini: {
      sheet: 'stage',
      frames: [
        { x: 152, y: 548, w: 14, h: 20 },
        { x: 167, y: 548, w: 14, h: 20 },
        { x: 182, y: 548, w: 14, h: 20 },
      ],
      fps: 3,
    },
    agent_team: {
      sheet: 'stage',
      frames: [
        { x: 280, y: 497, w: 34, h: 22 },
        { x: 315, y: 497, w: 34, h: 22 },
      ],
      fps: 3,
    },
    token: {
      sheet: 'stage',
      frames: [
        { x: 481, y: 589, w: 7, h: 7 },
        { x: 489, y: 589, w: 7, h: 7 },
        { x: 497, y: 589, w: 7, h: 7 },
        { x: 1, y: 601, w: 7, h: 7 },
      ],
      fps: 1,
    },
    token_small: {
      sheet: 'stage',
      frames: [
        { x: 196, y: 601, w: 5, h: 5 },
        { x: 202, y: 601, w: 5, h: 5 },
        { x: 208, y: 601, w: 5, h: 5 },
        { x: 214, y: 601, w: 5, h: 5 },
      ],
      fps: 1,
    },
    token_tilt: {
      sheet: 'stage',
      frames: [
        { x: 9, y: 601, w: 7, h: 7 },
        { x: 17, y: 601, w: 7, h: 7 },
        { x: 25, y: 601, w: 7, h: 7 },
        { x: 33, y: 601, w: 7, h: 7 },
      ],
      fps: 1,
    },
    manual: {
      sheet: 'stage',
      frames: [
        { x: 41, y: 601, w: 30, h: 5 },
        { x: 72, y: 601, w: 30, h: 5 },
        { x: 103, y: 601, w: 30, h: 5 },
        { x: 134, y: 601, w: 30, h: 5 },
        { x: 165, y: 601, w: 30, h: 5 },
      ],
      fps: 1,
    },
    wall_left: { sheet: 'stage', frames: [{ x: 322, y: 1, w: 64, h: 164 }] },
    wall_right: { sheet: 'stage', frames: [{ x: 387, y: 1, w: 64, h: 164 }] },
    scroll_summary: { sheet: 'stage', frames: [{ x: 113, y: 571, w: 38, h: 13 }] },
    glass_glare: { sheet: 'stage', frames: [{ x: 1, y: 182, w: 150, h: 150 }] },
    glass_crack: { sheet: 'stage', frames: [{ x: 152, y: 182, w: 150, h: 124 }] },
    gadget_grep: { sheet: 'stage', frames: [{ x: 329, y: 548, w: 18, h: 18 }] },
    gadget_grep_off: { sheet: 'stage', frames: [{ x: 348, y: 548, w: 18, h: 18 }] },
    gadget_read: { sheet: 'stage', frames: [{ x: 462, y: 548, w: 15, h: 18 }] },
    gadget_read_off: { sheet: 'stage', frames: [{ x: 478, y: 548, w: 15, h: 18 }] },
    gadget_edit: {
      sheet: 'stage',
      frames: [
        { x: 272, y: 548, w: 18, h: 18 },
        { x: 291, y: 548, w: 18, h: 18 },
      ],
      fps: 3,
    },
    gadget_edit_off: { sheet: 'stage', frames: [{ x: 310, y: 548, w: 18, h: 18 }] },
    gadget_bash: {
      sheet: 'stage',
      frames: [
        { x: 1, y: 571, w: 22, h: 17 },
        { x: 24, y: 571, w: 22, h: 17 },
      ],
      fps: 2,
    },
    gadget_bash_off: { sheet: 'stage', frames: [{ x: 47, y: 571, w: 22, h: 17 }] },
    gadget_web_search: {
      sheet: 'stage',
      frames: [
        { x: 367, y: 548, w: 18, h: 18 },
        { x: 386, y: 548, w: 18, h: 18 },
        { x: 405, y: 548, w: 18, h: 18 },
        { x: 424, y: 548, w: 18, h: 18 },
      ],
      fps: 4,
    },
    gadget_web_search_off: { sheet: 'stage', frames: [{ x: 443, y: 548, w: 18, h: 18 }] },
    gadget_subagent: {
      sheet: 'stage',
      frames: [
        { x: 197, y: 548, w: 14, h: 20 },
        { x: 212, y: 548, w: 14, h: 20 },
        { x: 227, y: 548, w: 14, h: 20 },
      ],
      fps: 3,
    },
    gadget_subagent_off: { sheet: 'stage', frames: [{ x: 242, y: 548, w: 14, h: 20 }] },
    gadget_mcp_server: {
      sheet: 'stage',
      frames: [
        { x: 223, y: 497, w: 18, h: 28 },
        { x: 242, y: 497, w: 18, h: 28 },
      ],
      fps: 2,
    },
    gadget_mcp_server_off: { sheet: 'stage', frames: [{ x: 261, y: 497, w: 18, h: 28 }] },
    gadget_agent_team: {
      sheet: 'stage',
      frames: [
        { x: 350, y: 497, w: 34, h: 22 },
        { x: 385, y: 497, w: 34, h: 22 },
      ],
      fps: 3,
    },
    gadget_agent_team_off: { sheet: 'stage', frames: [{ x: 420, y: 497, w: 34, h: 22 }] },
    gadget_ralph_loop: {
      sheet: 'stage',
      frames: [
        { x: 47, y: 548, w: 20, h: 20 },
        { x: 68, y: 548, w: 20, h: 20 },
        { x: 89, y: 548, w: 20, h: 20 },
        { x: 110, y: 548, w: 20, h: 20 },
      ],
      fps: 8,
    },
    gadget_ralph_loop_off: { sheet: 'stage', frames: [{ x: 131, y: 548, w: 20, h: 20 }] },
    gadget_rsi: {
      sheet: 'stage',
      frames: [
        { x: 455, y: 497, w: 22, h: 22 },
        { x: 478, y: 497, w: 22, h: 22 },
        { x: 1, y: 548, w: 22, h: 22 },
      ],
      fps: 4,
    },
    gadget_rsi_off: { sheet: 'stage', frames: [{ x: 24, y: 548, w: 22, h: 22 }] },
    pk_token_amber: { sheet: 'stage', frames: [{ x: 407, y: 571, w: 12, h: 12 }] },
    pk_chip_blue: { sheet: 'stage', frames: [{ x: 377, y: 571, w: 14, h: 12 }] },
    pk_bubble_white: { sheet: 'stage', frames: [{ x: 347, y: 571, w: 14, h: 12 }] },
    pk_bubble_amber: { sheet: 'stage', frames: [{ x: 332, y: 571, w: 14, h: 12 }] },
    pk_duck_amber: { sheet: 'stage', frames: [{ x: 392, y: 571, w: 14, h: 12 }] },
    pk_book_purple: { sheet: 'stage', frames: [{ x: 100, y: 571, w: 12, h: 14 }] },
    pk_bug_red: { sheet: 'stage', frames: [{ x: 362, y: 571, w: 14, h: 12 }] },
    pk_thumb_green: { sheet: 'stage', frames: [{ x: 86, y: 571, w: 13, h: 14 }] },
    pk_star_amber: { sheet: 'stage', frames: [{ x: 70, y: 571, w: 15, h: 15 }] },
    pk_mini_agent_green: { sheet: 'stage', frames: [{ x: 257, y: 548, w: 14, h: 20 }] },
  },
};

export default manifest;
