// GENERATED BY tools/art/build-art.mjs — do not edit by hand.
// Run `npm run art` to regenerate.
import type { AtlasManifest } from './atlas-types.ts';

const manifest: AtlasManifest = {
  sheets: {
    scenes: new URL('../../public/sprites/scenes.png', import.meta.url).href,
    objects: new URL('../../public/sprites/objects.png', import.meta.url).href,
  },
  sprites: {
    scene_bedroom: { sheet: 'scenes', frames: [{ x: 0, y: 0, w: 320, h: 180 }] },
    scene_coworking: { sheet: 'scenes', frames: [{ x: 0, y: 180, w: 320, h: 180 }] },
    scene_openplan: { sheet: 'scenes', frames: [{ x: 0, y: 360, w: 320, h: 180 }] },
    scene_datacenter: { sheet: 'scenes', frames: [{ x: 0, y: 540, w: 320, h: 180 }] },
    scene_orbital: { sheet: 'scenes', frames: [{ x: 0, y: 720, w: 320, h: 180 }] },
    laptop: {
      sheet: 'objects',
      frames: [
        { x: 1, y: 1, w: 64, h: 44 },
        { x: 66, y: 1, w: 64, h: 44 },
        { x: 131, y: 1, w: 64, h: 44 },
      ],
      fps: 12,
    },
    clutter_duck: { sheet: 'objects', frames: [{ x: 51, y: 46, w: 12, h: 12 }] },
    clutter_mug: { sheet: 'objects', frames: [{ x: 64, y: 46, w: 12, h: 12 }] },
    clutter_monitor: { sheet: 'objects', frames: [{ x: 77, y: 46, w: 40, h: 40 }] },
    clutter_terminal: {
      sheet: 'objects',
      frames: [
        { x: 118, y: 46, w: 40, h: 40 },
        { x: 159, y: 46, w: 40, h: 40 },
        { x: 200, y: 46, w: 40, h: 40 },
      ],
      fps: 4,
    },
    clutter_swarm: {
      sheet: 'objects',
      frames: [
        { x: 1, y: 87, w: 48, h: 34 },
        { x: 50, y: 87, w: 48, h: 34 },
        { x: 99, y: 87, w: 48, h: 34 },
      ],
      fps: 6,
    },
    clutter_loop: {
      sheet: 'objects',
      frames: [
        { x: 148, y: 87, w: 44, h: 36 },
        { x: 193, y: 87, w: 44, h: 36 },
        { x: 1, y: 124, w: 44, h: 36 },
      ],
      fps: 10,
    },
    clutter_rack: { sheet: 'objects', frames: [{ x: 46, y: 124, w: 40, h: 52 }] },
    clutter_fleet: {
      sheet: 'objects',
      frames: [
        { x: 87, y: 124, w: 44, h: 52 },
        { x: 132, y: 124, w: 44, h: 52 },
      ],
      fps: 4,
    },
    clutter_gpuwall: {
      sheet: 'objects',
      frames: [
        { x: 1, y: 177, w: 152, h: 26 },
        { x: 1, y: 204, w: 152, h: 26 },
        { x: 1, y: 231, w: 152, h: 26 },
      ],
      fps: 8,
    },
    clutter_agi: {
      sheet: 'objects',
      frames: [
        { x: 154, y: 231, w: 40, h: 40 },
        { x: 195, y: 231, w: 40, h: 40 },
        { x: 1, y: 272, w: 40, h: 40 },
      ],
      fps: 5,
    },
    dev_idle: {
      sheet: 'objects',
      frames: [
        { x: 196, y: 1, w: 24, h: 28 },
        { x: 221, y: 1, w: 24, h: 28 },
      ],
      fps: 2,
    },
    dev_type: {
      sheet: 'objects',
      frames: [
        { x: 1, y: 46, w: 24, h: 28 },
        { x: 26, y: 46, w: 24, h: 28 },
      ],
      fps: 8,
    },
  },
};

export default manifest;
