/**
 * Public surface of the renderer (the STAGE).
 *
 * `createRenderer(canvas)` returns a `SceneRenderer`: the frozen `Renderer`
 * from src/sim/types.ts plus `renderStats()`, `metrics()` and `whenReady()`.
 * It never throws: a host without a 2D context degrades to coordinate maths
 * plus a no-op `draw()`, and a missing atlas degrades to procedural art.
 */
export { STAGE_TEXT, createRenderer } from './scene.ts';
export type { RenderStats, RendererOptions, SceneRenderer, StageStats } from './scene.ts';

export {
  AGENT_BOX,
  AGENT_FEET,
  AGENT_RECT,
  GADGET_SPRITES,
  PICKUP_SPRITES,
  REQUIRED_SPRITES,
  gadgetSprites,
  pickupSprite,
} from './atlas-types.ts';
export type { AtlasManifest, SpriteDef, SpriteFrame } from './atlas-types.ts';

/** The UI icon sheet manifest (generated by tools/art/icons.mjs). */
export { ICONS, ICON_COLS, ICON_IDS, ICON_ROWS, ICON_SHEET, ICON_SIZE, iconPos } from './icon-map.ts';

export {
  CSS_VAR_PREFIX,
  PALETTE,
  PALETTE_KEYS,
  hexToRgb,
  mix,
  paletteCss,
  rgba,
  shade,
} from './palette.ts';
export type { PaletteKey, Rgb } from './palette.ts';

export {
  CHAR_ADVANCE,
  GLYPH_H,
  GLYPH_W,
  LINE_HEIGHT,
  SUPPORTED_CHARS,
  clearTextCache,
  drawText,
  formatCompact,
  formatContextShort,
  glyphRows,
  isSupported,
  measureText,
  textHeight,
} from './text.ts';
export type { TextOptions } from './text.ts';

export { MAX_DPR, computeScale, createSurface, hitsAgent } from './canvas.ts';
export type { ScaleResult, ViewMetrics, ViewportOptions } from './canvas.ts';

export { PARTICLE_CAP, ParticleSystem } from './particles.ts';
export { SpriteSystem } from './sprites.ts';
export { SCENE_KEYS, paintBackdrop, sceneAccent } from './backdrop.ts';
export { selectHuman, isAwayIncident, isHumanIncident, isPermissionIncident, isSuspicionIncident } from './human.ts';
export type { HumanInputs, HumanMood, HumanPose, HumanState, HumanView } from './human.ts';
export { selectAgent, agentSprite, bounceAt } from './agent.ts';
export type { AgentInputs, AgentState } from './agent.ts';
export { floorHeight, pileHeightAt, pilePeak, pileProfile, pileTopY } from './pile.ts';
export { AGENT_ORIGIN, AGENT_X, BAND, FEET_Y, FLOOR_Y, GADGET_SLOTS, GLASS, PILE_MAX_H } from './layout.ts';
