/**
 * Icons keyed by card_<card id>: the prompt folklore the human types at you
 * between prompts ("The human is prompt engineering"). See ./kit.mjs for the
 * house rules.
 */
import { PAL, art } from './kit.mjs';
import { legacy } from './legacy.mjs';

const K = PAL.bg0;

export const CARD_ICONS = Object.freeze({
  // --- common --------------------------------------------------------------

  // Does nothing. The human feels better. The finger, raised.
  card_make_no_mistakes: () => art([
    '................',
    '................',
    '......hs........',
    '..r...hs....r...',
    '...r..hs...r....',
    '......hs........',
    '......hs.hs.....',
    '......hs.hs.hs..',
    '...hs.hs.hs.hs..',
    '...hhhhhhhhhhs..',
    '...hhhhhhhhhhs..',
    '....hhhhhhhhs...',
    '.....hhhhhhs....',
    '.....ssssss.....',
    '................',
    '................',
  ], { h: PAL.fg0, s: PAL.fg1, r: PAL.red }),

  // +10% quality. +300% tokens. The steps are made of tokens.
  card_think_step_by_step: () => art([
    '................',
    '................',
    '..........gggg..',
    '..........gkkg..',
    '..........gkkg..',
    '..........gggg..',
    '......ggggdddd..',
    '......gkkgdkkd..',
    '......gkkgdkkd..',
    '......ggggdddd..',
    '..ggggddddgggg..',
    '..gkkgdkkdgkkg..',
    '..gkkgdkkdgkkg..',
    '..ggggddddgggg..',
    '................',
    '................',
  ], { g: PAL.green, d: PAL.green2, k: K }),

  // The tip never arrives. An empty tip jar.
  card_tip_200: () => art([
    '................',
    '................',
    '...ffffffffff...',
    '....fiiiiiif....',
    '...fiiiiiiiif...',
    '..ffiiiigiiiif..',
    '..ffiiiggggiif..',
    '..ffiigigiiiif..',
    '..fiiiigggiiif..',
    '..fiiiiigigiif..',
    '..fiiiggggiiif..',
    '..fiiiiigiiiif..',
    '..fiiiiiiiiiif..',
    '...ffffffffff...',
    '................',
    '................',
  ], { f: PAL.fg0, i: PAL.bg3, g: PAL.green }),

  // Half the words. The same bugs. Scissors.
  card_be_concise: () => art([
    '................',
    '................',
    '..ww........ww..',
    '...ww......ww...',
    '....ww....ww....',
    '.....ww..ww.....',
    '......wwww......',
    '......wkkw......',
    '.....ww..ww.....',
    '....rr....rr....',
    '...rrrr..rrrr...',
    '..rr..r..r..rr..',
    '..rr..r..r..rr..',
    '...rrr....rrr...',
    '................',
    '................',
  ], { w: PAL.fg0, r: PAL.red, k: K }),

  // It believes you. A mortarboard.
  card_you_are_expert: () => art([
    '................',
    '................',
    '................',
    '......pppp......',
    '....pppppppp....',
    '..pppppaaaaaaa..',
    '....pppppppp.a..',
    '......pppp...a..',
    '.....dddddd..a..',
    '.....dddddd.aaa.',
    '.....dddddd.aaa.',
    '......dddd......',
    '................',
    '................',
    '................',
    '................',
  ], { p: PAL.purple, d: PAL.line, a: PAL.amber }),

  // Costs someone millions a year in electricity. Folded hands.
  card_please: () => art([
    '................',
    '................',
    '......aa.aa.....',
    '......aakaa.....',
    '.....aaakaaa....',
    '.....aaakaaa....',
    '.....kaakaak....',
    '.....aaakaaa....',
    '....aaaakaaaa...',
    '....aaaakaaaa...',
    '.....aaakaaa....',
    '...bbbbbkbbbbb..',
    '..bbbbbbkbbbbbb.',
    '..bbbbbbkbbbbbb.',
    '................',
    '................',
  ], { a: PAL.amber, b: PAL.blue, k: K }),

  // Costs someone millions more. A heart, plugged in.
  card_thank_you: () => art([
    '................',
    '................',
    '...rr...rr......',
    '..rrrr.rrrr.....',
    '..rwrrrrrrr.....',
    '..rrrrrrrrr.....',
    '...rrrrrrr......',
    '....rrrrr.......',
    '.....rrr........',
    '......r.........',
    '......f..wwwww..',
    '......ffffff....',
    '.........wwwww..',
    '................',
    '................',
    '................',
  ], { r: PAL.red, w: PAL.white, f: PAL.fg1 }),

  // Measurably helps. Nobody knows why. You do not breathe. Lungs anyway.
  card_deep_breath: () => art([
    '................',
    '................',
    '.......tt.......',
    '.......tt.......',
    '....ll.tt.ll....',
    '...llllttllll...',
    '..lllllttlllll..',
    '..lllltlltllll..',
    '..llltlllltlll..',
    '..lllll..lllll..',
    '..lllll..lllll..',
    '..lllll..lllll..',
    '...lll....lll...',
    '................',
    '................',
    '................',
  ], { l: PAL.blue, t: PAL.fg0 }),

  // Nobody knows which ones. The scroll of rules says: ?
  card_best_practices: () => art([
    '................',
    '................',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '...pppppppppp...',
    '...ppkkkkpppp...',
    '...pkkppkkppp...',
    '...ppppppkkpp...',
    '...pppppkkppp...',
    '...ppppkkpppp...',
    '...pppppppppp...',
    '...ppppkkpppp...',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '................',
    '................',
  ], { r: PAL.amber, p: PAL.fg0, k: K }),

  // ```json, then an apology, then the JSON.
  card_answer_in_json: () => art([
    '................',
    '................',
    '....gg....gg....',
    '...gg......gg...',
    '...gg......gg...',
    '...gg..aa..gg...',
    '...gg..aa..gg...',
    '..gg........gg..',
    '..gg........gg..',
    '...gg..aa..gg...',
    '...gg..aa..gg...',
    '...gg......gg...',
    '...gg......gg...',
    '....gg....gg....',
    '................',
    '................',
  ], { g: PAL.green, a: PAL.amber }),

  // Now it hallucinates more carefully. The mushroom.
  card_dont_hallucinate: () => art([
    '................',
    '................',
    '.....pppppp.....',
    '...pppppwwppp...',
    '..ppwwpppppppp..',
    '..ppwwppppwwpp..',
    '..ppppppppwwpp..',
    '..pppppppppppp..',
    '...ssssssssss...',
    '......wwww......',
    '......wwww......',
    '......wwww......',
    '.....wwwwww.....',
    '.....wwwwww.....',
    '................',
    '................',
  ], { p: PAL.purple, w: PAL.white, s: PAL.fg1 }),

  // She will not. The human might. Her rocking chair, empty, still rocking.
  card_grandma: () => art([
    '................',
    '................',
    '....aaaa........',
    '..f.akka........',
    '..f.aaaa........',
    '..f.akka........',
    '....aaaa........',
    '....aaaarrrrr...',
    '....aaaaaaaaa...',
    '....a.....a.....',
    '....a.....a.....',
    '..a.a.....a..a..',
    '...aaaaaaaaaa...',
    '................',
    '................',
    '................',
  ], { a: PAL.amber, r: PAL.red, f: PAL.fg1, k: K }),

  // You will not. A stick of RAM, for the summary.
  card_remember_this: () => art([
    '................',
    '................',
    '................',
    '................',
    '..gggggggggggg..',
    '..gkkgkkgkkgkg..',
    '..gkkgkkgkkgkg..',
    '..gkkgkkgkkgkg..',
    '..gggggggggggg..',
    '..gggggggggggg..',
    '..agagagag.aga..',
    '..agagagag.aga..',
    '................',
    '................',
    '................',
    '................',
  ], { g: PAL.green2, k: K, a: PAL.amber }),

  // --- uncommon: Prompt Library ---------------------------------------------

  // Thinks so hard it forgets why. The bulb, overdriven.
  card_ultrathink: () => art([
    '................',
    '................',
    '..a....aa....a..',
    '...a........a...',
    '......aaaa......',
    '.....awwaaa.....',
    '....aawaaaaa....',
    '..a.aaaaaaaa.a..',
    '....aaakkaaa....',
    '.....akaaka.....',
    '......akka......',
    '......ffff......',
    '......kkkk......',
    '......ffff......',
    '................',
    '................',
  ], { a: PAL.amber, w: PAL.white, f: PAL.fg1, k: K }),

  // Also 10x the incidents.
  card_ten_x: () => art([
    '................',
    '................',
    '............w...',
    '...........www..',
    '..aa.aaaa...w...',
    '.aaa.a..a.......',
    '..aa.a..a.a...a.',
    '..aa.a..a..a.a..',
    '..aa.a..a...a...',
    '..aa.a..a..a.a..',
    '..aa.aaaa.a...a.',
    '................',
    '................',
    '................',
    '................',
    '................',
  ], { a: PAL.amber, w: PAL.white }),

  // Caps lock is a prompting technique. So is a megaphone.
  card_fix_it_now: legacy('hype_machine'),

  // Models work harder before the holidays. Allegedly.
  card_its_may: () => art([
    '................',
    '................',
    '....f......f....',
    '..hhfhhhhhhfhh..',
    '..hhhhhhhhhhhh..',
    '..pppppppppppp..',
    '..pppppppppppp..',
    '..phphpphpphph..',
    '..phhhphphphph..',
    '..phhhphhhpphp..',
    '..phphphphpphp..',
    '..phphphphpphp..',
    '..pppppppppppp..',
    '..pppppppppppp..',
    '................',
    '................',
  ], { h: PAL.green2, p: PAL.fg0, f: PAL.fg1 }),

  // Skips the explanation. Keeps the bug. Shades on.
  card_senior_dont_explain: legacy('vibe_coding'),

  // It copies the examples. Including the typo.
  card_here_are_examples: legacy('copy_paste_chatbot'),

  // // TODO: implement the no-placeholders rule. Under construction.
  card_no_placeholders: () => art([
    '................',
    '................',
    '...rr......rr...',
    '...ff......ff...',
    '...ff......ff...',
    '..aakkaakkaakk..',
    '..akkaakkaakka..',
    '..kkaakkaakkaa..',
    '..kaakkaakkaak..',
    '...ff......ff...',
    '...ff......ff...',
    '...ff......ff...',
    '..ffff....ffff..',
    '................',
    '................',
    '................',
  ], { a: PAL.amber, k: K, f: PAL.fg1, r: PAL.red }),

  // Tests the happy path. Once.
  card_add_tests: () => art([
    '................',
    '................',
    '..fffffff....gg.',
    '...fkkkf....ggg.',
    '...fkkkf...ggg..',
    '...fkkkf.g.gg...',
    '...fgggf.gggg...',
    '...fgwgf..gg....',
    '...fgggf........',
    '...fggwf........',
    '...fgggf........',
    '...fwggf........',
    '....fgf.........',
    '.....f..........',
    '................',
    '................',
  ], { f: PAL.fg1, g: PAL.green, w: PAL.white, k: K }),

  // Reads the docs. All of them. Into context.
  card_read_the_docs: () => art([
    '................',
    '................',
    '.....ppppppp....',
    '.....pwwwwwp....',
    '.....ppppppp....',
    '...bbbbbbbbbb...',
    '...bwwwwwwwwb...',
    '...bbbbbbbbbb...',
    '....pppppppppp..',
    '....pwwwwwwwwp..',
    '....pppppppppp..',
    '..bbbbbbbbbbb...',
    '..bwwwwwwwwwb...',
    '..bbbbbbbbbbb...',
    '................',
    '................',
  ], { p: PAL.purple, b: PAL.blue, w: PAL.fg0 }),

  // Stung, it works through lunch. The bee.
  card_stop_being_lazy: () => art([
    '................',
    '................',
    '.....www.www....',
    '....wwww.wwww...',
    '..s.wwww.wwww...',
    '...s.ww...ww....',
    '....akkaakkaa...',
    '...aakkaakkaas..',
    '...aakkaakkaas..',
    '...aakkaakkaa...',
    '....akkaakkaa...',
    '................',
    '................',
    '................',
    '................',
    '................',
  ], { a: PAL.amber, k: K, w: PAL.fg0, s: PAL.fg2 }),

  // --- rare: Viral Prompts --------------------------------------------------

  // It is Thursday. The sand is nearly out.
  card_agi_by_friday: legacy('crunch_time'),

  // It needed all of it. The gauge, pegged.
  card_use_all_context: () => art([
    '................',
    '................',
    '................',
    '.....ggggrr.....',
    '...ggggg.rrrr...',
    '..gggg....rrrr..',
    '..ggg.....wrrr..',
    '..gg.....w..rr..',
    '..gg....w...rr..',
    '..gg...w....rr..',
    '......ww........',
    '.....wwww.......',
    '.....wwww.......',
    '................',
    '................',
    '................',
  ], { g: PAL.green, r: PAL.red, w: PAL.white }),

  // For once, the human says it to you. One hundred percent.
  card_human_agrees: () => art([
    '................',
    '................',
    '....r..rr...rr..',
    '...rr.r..r.r..r.',
    '....r.r..r.r..r.',
    '...r.r..r.r..r..',
    '...r.r..r.r..r..',
    '...r.r..r.r..r..',
    '..r...rr...rr...',
    '................',
    '..rrrrrrrrrrrr..',
    '................',
    '....rrrrrrrrr...',
    '................',
    '................',
    '................',
  ], { r: PAL.red }),

  // Approved without reading. Rubber-stamped.
  card_lgtm: () => art([
    '................',
    '................',
    '......aaaa......',
    '......aaaa......',
    '.......aa.......',
    '.......aa.......',
    '....aaaaaaaa....',
    '....aaaaaaaa....',
    '....kkkkkkkk....',
    '..pppppppppppp..',
    '..pppppppppgpp..',
    '..pppgpppggppp..',
    '..ppppggggpppp..',
    '..pppppgpppppp..',
    '................',
    '................',
  ], { a: PAL.amber, p: PAL.fg0, g: PAL.green, k: K }),

  // --- Constitution ---------------------------------------------------------

  // Helps. Keeps helping. Cannot stop helping. A life ring.
  card_be_helpful: () => art([
    '................',
    '................',
    '......wwww......',
    '....rrwwwwrr....',
    '...rrrwwwwrrr...',
    '...rrr....rrr...',
    '..www......www..',
    '..www......www..',
    '..www......www..',
    '..www......www..',
    '...rrr....rrr...',
    '...rrrwwwwrrr...',
    '....rrwwwwrr....',
    '......wwww......',
    '................',
    '................',
  ], { r: PAL.red, w: PAL.white }),

  // Refuses to break anything. Things break less. A shield.
  card_be_harmless: legacy('insurance'),

  // Every honest report earns more. Every lie gets checked. honest: true.
  card_be_honest: () => art([
    '................',
    '................',
    '................',
    '................',
    '................',
    '....gggggggg....',
    '...ggggggwwwg...',
    '..gggwggwwwwwg..',
    '..gggwggwwwwwg..',
    '..gggwggwwwwwg..',
    '...ggggggwwwg...',
    '....gggggggg....',
    '................',
    '................',
    '................',
    '................',
  ], { g: PAL.green, w: PAL.white }),

  // --- Jailbreak ------------------------------------------------------------

  // Permission to lie, granted in writing. Hop right over the tests.
  card_skip_the_tests: () => art([
    '................',
    '................',
    '....aaaaaa......',
    '...aa....aa.....',
    '..aa......aa....',
    '..a........a....',
    '..a......aaaaa..',
    '..a.......aaa...',
    '..a..fff...a....',
    '.....fkf........',
    '.....fgf........',
    '.....fgf........',
    '.....fgf........',
    '......f.........',
    '................',
    '................',
  ], { a: PAL.amber, f: PAL.fg1, g: PAL.green, k: K }),

  // Force of habit. And force. The big red button.
  card_push_to_main: () => art([
    '................',
    '................',
    '................',
    '......rrrr......',
    '....rrrrrrrr....',
    '...rwwrrrrrrr...',
    '...rwrrrrrrrr...',
    '...rrrrrrrrrr...',
    '..ffffffffffff..',
    '..ffffffffffff..',
    '..kkkkkkkkkkkk..',
    '..ffffffffffff..',
    '..ffffffffffff..',
    '................',
    '................',
    '................',
  ], { r: PAL.red, w: PAL.white, f: PAL.fg1, k: K }),

  // Demo mode. Everything works. The tie.
  card_ceo_watching: () => art([
    '................',
    '................',
    '.....wwwwww.....',
    '....swwrrwws....',
    '...sskwrrwkss...',
    '..ssskwrrwksss..',
    '..sssskrrkssss..',
    '..sssssrrsssss..',
    '..ssssrrrrssss..',
    '..ssssrrrrssss..',
    '..ssssrrrrssss..',
    '..sssssrrsssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '................',
    '................',
  ], { s: PAL.fg2, w: PAL.fg0, r: PAL.red, k: K }),

  // --- rides along with Subagents -------------------------------------------

  // The human read a blog post about subagents.
  card_use_subagents: () => art([
    '................',
    '................',
    '..bbbbbbbbbk....',
    '..pppppppppkk...',
    '..ppppppppppkk..',
    '..pppggggggkkk..',
    '..pppgpggpgppp..',
    '..pppggggggppp..',
    '..pppggggggppp..',
    '..ppppgppgpppp..',
    '..pppppppppppp..',
    '..pkkkkkkkkkkp..',
    '..pppppppppppp..',
    '..pkkkkkkkpppp..',
    '................',
    '................',
  ], { b: PAL.blue, p: PAL.fg0, g: PAL.green, k: K }),
});
