/**
 * Icons are referenced by convention (tool_<id>, upg_<id>, card_<id>,
 * meta_<id>, pickup_<id>, the achievement's own `icon`, and a handful of
 * ui_* chrome ids), and icon-map.ts, generated by tools/art/icons.mjs, is the
 * one table from id to sheet cell.
 *
 * A missing icon degrades to a neutral tile, so nothing here can be caught by
 * a typecheck or a smoke test: it needs its own assertions.
 */
import { describe, expect, it } from 'vitest';
import { ACHIEVEMENTS, CARDS, META_UPGRADES, PICKUPS, TOOLS, UPGRADES } from '../../src/sim/content.ts';
import { cardIcon, metaIcon, pickupIcon, requiredIconIds, toolIcon, UI_ICONS, upgradeIcon } from '../../src/ui/icon-ids.ts';
import { ICONS, ICON_COLS, ICON_ROWS } from '../../src/ui/icon-map.ts';
import { hasIcon, iconEl, iconOrGlyph } from '../../src/ui/icon.ts';
import { makeRun, mountUI, unmountAll } from './ui.fake-sim.ts';

describe('the naming convention', () => {
  it('derives every id from its content id', () => {
    expect(toolIcon('grep')).toBe('tool_grep');
    expect(upgradeIcon('streaming')).toBe('upg_streaming');
    expect(cardIcon('please')).toBe('card_please');
    expect(metaIcon('helpful')).toBe('meta_helpful');
    expect(pickupIcon('golden_token')).toBe('pickup_golden_token');
    expect(Object.values(UI_ICONS).sort()).toEqual(['ui_claim', 'ui_compact', 'ui_context', 'ui_patience', 'ui_thumbs']);
  });

  it('asks the sheet for exactly one id per thing, and no two things share one', () => {
    const ids = requiredIconIds();
    expect(new Set(ids).size).toBe(ids.length);
    const expected =
      TOOLS.length + UPGRADES.length + CARDS.length + META_UPGRADES.length + PICKUPS.length + ACHIEVEMENTS.length + 5;
    expect(ids).toHaveLength(expected);
    for (const a of ACHIEVEMENTS) expect(ids).toContain(a.icon);
  });

  it('never renders an icon id the sheet was not told about', () => {
    const wanted = new Set(requiredIconIds());
    const m = mountUI({
      screen: 'run',
      run: makeRun({ tokens: 1e6, cards: ['please', 'grandma'] }),
      upgrades: ['streaming', 'prompt_caching'],
    });
    m.ui.handle({ t: 'achievement', id: 'compacted' });
    for (const s of ['meta', 'achievements', 'run'] as const) {
      m.ui.setScreen(s);
      m.frame();
    }
    const seen = Array.from(m.root.querySelectorAll<HTMLElement>('[data-icon]'), (n) => n.dataset['icon'] ?? '');
    expect(seen.length).toBeGreaterThan(30);
    const stray = seen.filter((id) => !wanted.has(id));
    expect(stray, `rendered but not in requiredIconIds(): ${stray.join(', ')}`).toEqual([]);
    unmountAll();
  });
});

describe('icon tiles', () => {
  it('positions a known id into the sheet and marks an unknown one', () => {
    const known = Object.keys(ICONS)[0];
    if (known !== undefined) {
      const tile = iconEl(known);
      expect(tile.style.getPropertyValue('--ix')).toBe(String(ICONS[known]![0]));
      expect(tile.classList.contains('tm-icon--missing')).toBe(false);
    }
    const hole = iconEl('definitely_not_an_icon');
    expect(hole.classList.contains('tm-icon--missing')).toBe(true);
    expect(hole.getAttribute('aria-hidden')).toBe('true');
  });

  it('falls back to a glyph painted by CSS, so the text around it never changes', () => {
    const g = iconOrGlyph('definitely_not_an_icon', '👍');
    expect(g.textContent).toBe('');
    expect(g.dataset['glyph']).toBe('👍');
  });
});

/**
 * The STAGE agent draws the sheet with exactly `requiredIconIds()`. Until the
 * regenerated icon-map.ts lands, the checked-in map is still the first game's,
 * and these checks would only list every id as missing.
 */
const sheetIsTheSequels = Object.keys(ICONS).some((id) => id.startsWith('tool_'));

describe.skipIf(!sheetIsTheSequels)('the regenerated sheet', () => {
  it('has a cell for every id the UI asks for', () => {
    const missing = requiredIconIds().filter((id) => !hasIcon(id));
    expect(missing, `add these to tools/art/icons.mjs:\n  ${missing.join('\n  ')}`).toEqual([]);
  });

  it('fits inside the generated grid, one icon per cell', () => {
    for (const [id, [x, y]] of Object.entries(ICONS)) {
      expect(x, `${id} column`).toBeLessThan(ICON_COLS);
      expect(y, `${id} row`).toBeLessThan(ICON_ROWS);
    }
    const cells = Object.values(ICONS).map(([x, y]) => `${x},${y}`);
    expect(new Set(cells).size, 'two icons share a cell').toBe(cells.length);
  });
});
